// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/58ee4d2d6f295eb74cf1.svg"
    | "/6d076abcfd16e9f4ad0b.png"
    | "/audio/attention-1.mp3"
    | "/audio/attention-2.mp3"
    | "/audio/beep-off.mp3"
    | "/audio/beep-on.mp3"
    | "/audio/call-failed.mp3"
    | "/audio/send-round-long.mp3"
    | "/audio/send-round-short.mp3"
    | "/audio/startup-synth.mp3"
    | "/audio/switch-off.mp3"
    | "/audio/switch-on.mp3"
    | "/audio/synthetic-speech.wav"
    | "/audio/synthetic-speech/01.wav"
    | "/audio/synthetic-speech/02.wav"
    | "/audio/synthetic-speech/03.wav"
    | "/audio/synthetic-speech/04.wav"
    | "/audio/synthetic-speech/05.wav"
    | "/audio/synthetic-speech/06.wav"
    | "/audio/synthetic-speech/07.wav"
    | "/audio/synthetic-speech/08.wav"
    | "/audio/test-tone.mp3"
    | "/audio/turn-off.mp3"
    | "/background.js"
    | "/content-scripts/saypi-universal.js"
    | "/content-scripts/saypi.js"
    | "/d54c339478aa04913da7.svg"
    | "/icons/logos/elevenlabs.svg"
    | "/icons/logos/inflection.ai.png"
    | "/icons/logos/openai.svg"
    | "/icons/logos/saypi.png"
    | "/icons/microphone-muted.svg"
    | "/icons/microphone-switch.svg"
    | "/icons/microphone.svg"
    | "/icons/sixty-seconds.svg"
    | "/logos/marquee.png"
    | "/offscreen.html"
    | "/ort-wasm-simd-threaded.mjs"
    | "/permissions.html"
    | "/settings.html"
    | "/silero_vad.onnx"
    | "/silero_vad_legacy.onnx"
    | "/silero_vad_v5.onnx"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
