export const KEEP_ALIVE_INTERVAL_MS = 12000;
export const MAX_KEEP_ALIVES_PER_TOOL_USE = 10;
export const KEEP_ALIVE_RATE_WINDOW_MS = KEEP_ALIVE_INTERVAL_MS;
export const MAX_KEEP_ALIVES_PER_RATE_WINDOW = 2;
